name: Dart CI

on:
  push:
    branches: [ dev_cicd_tests ]
  pull_request:
    branches: [ dev_cicd_tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.12.14'
        channel: 'dev'
    - name: Install dependencies
      run: flutter pub get
    - name: Static analysis
      run: flutter  analyze
    - name: Running tests
      run: flutter test --coverage
